# Sentence Embedding with Logistic Regression Model

In [ ]:
import numpy as np
import pandas as pd
import nltk

In [2]:
df=pd.read_csv('\\data wrangling\\data\\news.csv')

In [3]:
df.head()

,title,content,published_at,source,topic
0,BTS: RM is reminded of Bon Voyage as he travel...,"After reaching his hotel in the city, RM revea...",2022-07-30T07:00:00Z,2,13
1,RM recalls wondering if he 'made right decisio...,RM aka Kim Namjoon was the first member to joi...,2022-12-22T15:57:55Z,2,13
2,BTS: J-Hope and RM go bonkers at Billie Eilish...,"Billie Eilish's concert was held in Seoul, Sou...",2022-08-16T07:00:00Z,1,7
3,"BTS: J-Hope proudly states he raised Jungkook,...",BTS ARMY y'all would be missing the members a ...,2022-12-18T13:08:40Z,1,7
4,BTS: Jin aka Kim Seokjin takes us through the ...,BTS member Kim Seokjin aka Jin has the capacit...,2022-11-21T08:00:00Z,1,8

In [4]:
df.shape

(810, 5)

In [5]:
#Lowercasing text
df['content']=df['content'][3].lower()

In [6]:
df['title']=df['title'].str.lower()

In [7]:
df

,title,content,published_at,source,topic
0,bts: rm is reminded of bon voyage as he travel...,bts army y'all would be missing the members a ...,2022-07-30T07:00:00Z,2,13
1,rm recalls wondering if he 'made right decisio...,bts army y'all would be missing the members a ...,2022-12-22T15:57:55Z,2,13
2,bts: j-hope and rm go bonkers at billie eilish...,bts army y'all would be missing the members a ...,2022-08-16T07:00:00Z,1,7
3,"bts: j-hope proudly states he raised jungkook,...",bts army y'all would be missing the members a ...,2022-12-18T13:08:40Z,1,7
4,bts: jin aka kim seokjin takes us through the ...,bts army y'all would be missing the members a ...,2022-11-21T08:00:00Z,1,8
...,...,...,...,...,...
805,bts’ suga’s suchwita ep 2 teaser out: top 3 so...,bts army y'all would be missing the members a ...,2022-12-30T08:00:00Z,3,11
806,bts army celebrate 700 days of jin's special s...,bts army y'all would be missing the members a ...,2022-01-20T08:00:00Z,3,8
807,"bts: 'i am not a baby,' says jungkook as an ar...",bts army y'all would be missing the members a ...,2022-09-02T07:00:00Z,1,10
808,bts' jin shares 1st pics after joining militar...,bts army y'all would be missing the members a ...,2023-01-18T08:36:56Z,2,1
809,"bad decisions: bts’ jin, jimin, v & jungkook j...",bts army y'all would be missing the members a ...,2022-08-05T07:00:00Z,3,8

In [8]:
#removing tag from the text
import re
def remove_html_tags(df):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',df)

In [9]:
df['content']=df['content'].apply(remove_html_tags)

In [10]:
df['title']=df['title'].apply(remove_html_tags)

In [11]:
#Remove panctuation
import string
exclude = string.punctuation

In [12]:
def remove_punc(df):
    return df.translate(str.maketrans("","",exclude))

In [13]:
df['title']=df['title'].apply(remove_punc)

In [14]:
df['content']=df['content'].apply(remove_punc)

In [15]:
df

,title,content,published_at,source,topic
0,bts rm is reminded of bon voyage as he travels...,bts army yall would be missing the members a l...,2022-07-30T07:00:00Z,2,13
1,rm recalls wondering if he made right decision...,bts army yall would be missing the members a l...,2022-12-22T15:57:55Z,2,13
2,bts jhope and rm go bonkers at billie eilishs ...,bts army yall would be missing the members a l...,2022-08-16T07:00:00Z,1,7
3,bts jhope proudly states he raised jungkook ji...,bts army yall would be missing the members a l...,2022-12-18T13:08:40Z,1,7
4,bts jin aka kim seokjin takes us through the s...,bts army yall would be missing the members a l...,2022-11-21T08:00:00Z,1,8
...,...,...,...,...,...
805,bts’ suga’s suchwita ep 2 teaser out top 3 sol...,bts army yall would be missing the members a l...,2022-12-30T08:00:00Z,3,11
806,bts army celebrate 700 days of jins special so...,bts army yall would be missing the members a l...,2022-01-20T08:00:00Z,3,8
807,bts i am not a baby says jungkook as an army s...,bts army yall would be missing the members a l...,2022-09-02T07:00:00Z,1,10
808,bts jin shares 1st pics after joining military...,bts army yall would be missing the members a l...,2023-01-18T08:36:56Z,2,1
809,bad decisions bts’ jin jimin v jungkook join ...,bts army yall would be missing the members a l...,2022-08-05T07:00:00Z,3,8

In [16]:
# short word treatment

In [17]:
def text_conversation(df):
    new_df = []
    for w in df.split():
        if w.upper() in df:
            new_df.append(df[w.upper()])
        else:
            new_df.append(w)
    return " ".join(new_df)

In [18]:

df['content']=df['content'].apply(text_conversation)
df['content']

0      bts army yall would be missing the members a l...
1      bts army yall would be missing the members a l...
2      bts army yall would be missing the members a l...
3      bts army yall would be missing the members a l...
4      bts army yall would be missing the members a l...
                             ...
805    bts army yall would be missing the members a l...
806    bts army yall would be missing the members a l...
807    bts army yall would be missing the members a l...
808    bts army yall would be missing the members a l...
809    bts army yall would be missing the members a l...
Name: content, Length: 810, dtype: object

In [19]:
df

,title,content,published_at,source,topic
0,bts rm is reminded of bon voyage as he travels...,bts army yall would be missing the members a l...,2022-07-30T07:00:00Z,2,13
1,rm recalls wondering if he made right decision...,bts army yall would be missing the members a l...,2022-12-22T15:57:55Z,2,13
2,bts jhope and rm go bonkers at billie eilishs ...,bts army yall would be missing the members a l...,2022-08-16T07:00:00Z,1,7
3,bts jhope proudly states he raised jungkook ji...,bts army yall would be missing the members a l...,2022-12-18T13:08:40Z,1,7
4,bts jin aka kim seokjin takes us through the s...,bts army yall would be missing the members a l...,2022-11-21T08:00:00Z,1,8
...,...,...,...,...,...
805,bts’ suga’s suchwita ep 2 teaser out top 3 sol...,bts army yall would be missing the members a l...,2022-12-30T08:00:00Z,3,11
806,bts army celebrate 700 days of jins special so...,bts army yall would be missing the members a l...,2022-01-20T08:00:00Z,3,8
807,bts i am not a baby says jungkook as an army s...,bts army yall would be missing the members a l...,2022-09-02T07:00:00Z,1,10
808,bts jin shares 1st pics after joining military...,bts army yall would be missing the members a l...,2023-01-18T08:36:56Z,2,1
809,bad decisions bts’ jin jimin v jungkook join ...,bts army yall would be missing the members a l...,2022-08-05T07:00:00Z,3,8

In [20]:
#new_df=df.applymap(str)
#textBlb = TextBlob(new_df)
#textBlb.correct().string

In [21]:
import re
def tokenization(text):
    tokens = re.split('W+',text)
    return tokens
#applying function to the column
df['content']= df['content'].apply(lambda x: tokenization(x))

In [22]:
df['title']=df['title'].apply(lambda x: tokenization(x))

In [23]:
df

,title,content,published_at,source,topic
0,[bts rm is reminded of bon voyage as he travel...,[bts army yall would be missing the members a ...,2022-07-30T07:00:00Z,2,13
1,[rm recalls wondering if he made right decisio...,[bts army yall would be missing the members a ...,2022-12-22T15:57:55Z,2,13
2,[bts jhope and rm go bonkers at billie eilishs...,[bts army yall would be missing the members a ...,2022-08-16T07:00:00Z,1,7
3,[bts jhope proudly states he raised jungkook j...,[bts army yall would be missing the members a ...,2022-12-18T13:08:40Z,1,7
4,[bts jin aka kim seokjin takes us through the ...,[bts army yall would be missing the members a ...,2022-11-21T08:00:00Z,1,8
...,...,...,...,...,...
805,[bts’ suga’s suchwita ep 2 teaser out top 3 so...,[bts army yall would be missing the members a ...,2022-12-30T08:00:00Z,3,11
806,[bts army celebrate 700 days of jins special s...,[bts army yall would be missing the members a ...,2022-01-20T08:00:00Z,3,8
807,[bts i am not a baby says jungkook as an army ...,[bts army yall would be missing the members a ...,2022-09-02T07:00:00Z,1,10
808,[bts jin shares 1st pics after joining militar...,[bts army yall would be missing the members a ...,2023-01-18T08:36:56Z,2,1
809,[bad decisions bts’ jin jimin v jungkook join...,[bts army yall would be missing the members a ...,2022-08-05T07:00:00Z,3,8

In [24]:
import nltk
#Stop words present in the library
stopwords = nltk.corpus.stopwords.words('english')
stopwords[0:10]
#['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [25]:
#defining the function to remove stopwords from tokenized text
def remove_stopwords(text):
    output= [i for i in text if i not in stopwords]
    return output

In [26]:
#applying the function
df['title']= df['title'].apply(lambda x:remove_stopwords(x))
df['content']=df['content'].apply(lambda x:remove_stopwords(x))
df

,title,content,published_at,source,topic
0,[bts rm is reminded of bon voyage as he travel...,[bts army yall would be missing the members a ...,2022-07-30T07:00:00Z,2,13
1,[rm recalls wondering if he made right decisio...,[bts army yall would be missing the members a ...,2022-12-22T15:57:55Z,2,13
2,[bts jhope and rm go bonkers at billie eilishs...,[bts army yall would be missing the members a ...,2022-08-16T07:00:00Z,1,7
3,[bts jhope proudly states he raised jungkook j...,[bts army yall would be missing the members a ...,2022-12-18T13:08:40Z,1,7
4,[bts jin aka kim seokjin takes us through the ...,[bts army yall would be missing the members a ...,2022-11-21T08:00:00Z,1,8
...,...,...,...,...,...
805,[bts’ suga’s suchwita ep 2 teaser out top 3 so...,[bts army yall would be missing the members a ...,2022-12-30T08:00:00Z,3,11
806,[bts army celebrate 700 days of jins special s...,[bts army yall would be missing the members a ...,2022-01-20T08:00:00Z,3,8
807,[bts i am not a baby says jungkook as an army ...,[bts army yall would be missing the members a ...,2022-09-02T07:00:00Z,1,10
808,[bts jin shares 1st pics after joining militar...,[bts army yall would be missing the members a ...,2023-01-18T08:36:56Z,2,1
809,[bad decisions bts’ jin jimin v jungkook join...,[bts army yall would be missing the members a ...,2022-08-05T07:00:00Z,3,8

In [27]:
df=df.astype(str)
print(df.dtypes)

title           object
content         object
published_at    object
source          object
topic           object
dtype: object

In [28]:
df

,title,content,published_at,source,topic
0,['bts rm is reminded of bon voyage as he trave...,['bts army yall would be missing the members a...,2022-07-30T07:00:00Z,2,13
1,['rm recalls wondering if he made right decisi...,['bts army yall would be missing the members a...,2022-12-22T15:57:55Z,2,13
2,['bts jhope and rm go bonkers at billie eilish...,['bts army yall would be missing the members a...,2022-08-16T07:00:00Z,1,7
3,['bts jhope proudly states he raised jungkook ...,['bts army yall would be missing the members a...,2022-12-18T13:08:40Z,1,7
4,['bts jin aka kim seokjin takes us through the...,['bts army yall would be missing the members a...,2022-11-21T08:00:00Z,1,8
...,...,...,...,...,...
805,['bts’ suga’s suchwita ep 2 teaser out top 3 s...,['bts army yall would be missing the members a...,2022-12-30T08:00:00Z,3,11
806,['bts army celebrate 700 days of jins special ...,['bts army yall would be missing the members a...,2022-01-20T08:00:00Z,3,8
807,['bts i am not a baby says jungkook as an army...,['bts army yall would be missing the members a...,2022-09-02T07:00:00Z,1,10
808,['bts jin shares 1st pics after joining milita...,['bts army yall would be missing the members a...,2023-01-18T08:36:56Z,2,1
809,['bad decisions bts’ jin jimin v jungkook joi...,['bts army yall would be missing the members a...,2022-08-05T07:00:00Z,3,8

In [29]:
!pip install -U transformers

Requirement already satisfied: transformers in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (4.26.0)
Requirement already satisfied: requests in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (2.28.1)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python310\site-packages (from transformers) (21.3)
Requirement already satisfied: numpy>=1.17 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (1.22.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (0.13.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (6.0)
Requirement already satisfied: filelock in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (3.9.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (2022.9.13)
Requirement already satisfied: tqdm>=4.27 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (4.64.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from transformers) (0.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from huggingface-hub<1.0,>=0.11.0->transformers) (4.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\hp\appdata\roaming\python\python310\site-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python310\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from requests->transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from requests->transformers) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hp\anaconda3\envs\myenv\lib\site-packages (from requests->transformers) (1.26.11)

In [30]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

In [31]:
df['embeddings']=df['title'].apply(model.encode)

In [32]:
df['Embeddings']=df['content'].apply(model.encode)

In [33]:
df

,title,content,published_at,source,topic,embeddings,Embeddings
0,['bts rm is reminded of bon voyage as he trave...,['bts army yall would be missing the members a...,2022-07-30T07:00:00Z,2,13,"[0.0039185775, 0.021853583, -0.0104972925, -0....","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
1,['rm recalls wondering if he made right decisi...,['bts army yall would be missing the members a...,2022-12-22T15:57:55Z,2,13,"[-0.022283886, 0.021071639, -0.02178587, -0.04...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
2,['bts jhope and rm go bonkers at billie eilish...,['bts army yall would be missing the members a...,2022-08-16T07:00:00Z,1,7,"[-0.09083636, -0.0305467, 0.037264995, -0.0912...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
3,['bts jhope proudly states he raised jungkook ...,['bts army yall would be missing the members a...,2022-12-18T13:08:40Z,1,7,"[-0.07855974, 0.0502289, -0.0096692685, -0.011...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
4,['bts jin aka kim seokjin takes us through the...,['bts army yall would be missing the members a...,2022-11-21T08:00:00Z,1,8,"[-0.06988014, 0.035368834, 0.036416207, -0.041...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
...,...,...,...,...,...,...,...
805,['bts’ suga’s suchwita ep 2 teaser out top 3 s...,['bts army yall would be missing the members a...,2022-12-30T08:00:00Z,3,11,"[-0.06686764, -0.038809624, -0.0395136, -0.035...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
806,['bts army celebrate 700 days of jins special ...,['bts army yall would be missing the members a...,2022-01-20T08:00:00Z,3,8,"[-0.08955837, 0.059989084, 0.031217761, -0.024...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
807,['bts i am not a baby says jungkook as an army...,['bts army yall would be missing the members a...,2022-09-02T07:00:00Z,1,10,"[-0.060786474, 0.102025054, 0.019358158, 0.055...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
808,['bts jin shares 1st pics after joining milita...,['bts army yall would be missing the members a...,2023-01-18T08:36:56Z,2,1,"[-0.09157225, -0.0032913343, 0.05195772, 0.013...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."
809,['bad decisions bts’ jin jimin v jungkook joi...,['bts army yall would be missing the members a...,2022-08-05T07:00:00Z,3,8,"[-0.10971461, 0.014147914, -0.074508645, -0.04...","[-0.0792996, 0.016180288, 0.041469034, -0.0234..."

In [47]:
x=df['embeddings'].to_list()
y=df['source'].to_list()

In [48]:
# Logistic Regression model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.1,stratify=y)

In [49]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(x_train, y_train)

LogisticRegression()

In [52]:
from sklearn import metrics 
predicted=LR.predict(x_test)
print('Logistic Regression Accuracy:', metrics.accuracy_score(y_test, predicted))

print('Logistic Regression Precision:', metrics.precision_score(y_test, predicted,pos_label='positive',average='macro'))
print('Logistic Regression Recall:', metrics.recall_score(y_test, predicted,pos_label='positive',average='micro'))

Logistic Regression Accuracy: 0.5925925925925926
Logistic Regression Precision: 0.726165501165501
Logistic Regression Recall: 0.5925925925925926

C:\Users\hp\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
C:\Users\hp\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(